// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arkvkqjjnoedkejrgmeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFya3ZrcWpqbm9lZGtlanJnbWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTk3ODEsImV4cCI6MjA2NTQ5NTc4MX0.4YvQ-XlBcwflqhz3X6SlAm0RpPAIatqDvY1bkQCgdpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);